### ISSUE TITLE
Custom Added Skills not Saving to User Profile

### ISSUE THREAD

**Issue by bshores** [Code4SocialGood/c4sg-web#674] opened 2017-07-05 22:28 UTC
**Description**:
As a user when I create a new user, and add a custom skill. After I click save the custom skill should be saved to that user for later use. 

**Assumptions**:
No user Created

**Test Case:**

1. Create a new user, verify email.
2. Login using the newly created user
3. Click dropdown for the user in the top right
4. Click My Settings
5. Under my skills, add a custom skill - Example, Automation
6. Click save

**Expected Result:**
Adding a skill to my user should save, after clicking the save button. 

**Actual Result:**
When navigating back to the volunteer screen the added skills do not show up. When going back into my settings, the skills never successfully saved to the user profile

**Comment by Code4SocialGood** [comment] 2017-07-06 03:23
#672, #673 and #674 are issues with same root cause. They will be fixed in one PR.

**Comment by Code4SocialGood** [comment] 2017-07-07 23:54
@bshores This issue is resolved in PR #703. Please retest.

**Comment by Code4SocialGood** [comment] 2017-07-16 02:55
Issue is resolved in PR #703.

**Closed by Code4SocialGood** 2017-07-16 02:55 UTC
Labels: Test
