### ISSUE TITLE
Skills Tags Not Saving to User Profile

### ISSUE THREAD

**Issue by bshores** [Code4SocialGood/c4sg-web#672] opened 2017-07-05 22:22 UTC
**Description:**
As a user when I create a new user, and add a skill; I want the newly added skill to show as a tag in the volunteer search. This tag should be recognized by the filters. As a user who has experience with Ruby when an individual is searching the site, all users with ruby skills should appear.  When adding the skills through "My Settings" it should save to the users profile

**Assumptions:**
No user Created

**Test Case:**
1. Create a new user, verify email. 
2. Login using the newly created user
3. Click dropdown for the user in the top right
4. Click My Settings
5. Under my skills, add skills from the drop down menu Example I selected Ruby
6. Click save
7. Click Volunteers link in the top navigation
8. The check menus on the left of the page, show skills that are available to search from
9. Select the "Ruby" box

**Expected Result:**
When a user adds a skill, the skill should then be able to be filtered by when the user goes back to the volunteer page and searches for volunteers with specific skills

**Actual Result:**
The skill is not being saved to the record, and is not allowing the user to sort and filter by that skill

**Comment by Code4SocialGood** [comment] 2017-07-06 03:19
The issue could be recreated as below:
1. Login as volunteer user:  testvolunteeruser2@gmail.com / Opensource5social!
2. From drop down, click My Settings
3. There is one skill tag shown for this user: css
4. From the skills drop down, select another tag: Ruby
5. Click Save
6. System throws a toast: "Your change has been save.". And you are redirected to User View page.
7. In the user view page, you can see that the added skill, Ruby, is not shown.

Checking the backend database, this new skill has not been added to the database.

**Comment by Code4SocialGood** [comment] 2017-07-06 03:24
#672, #673 and #674 are issues with same root cause. They will be fixed in one PR.

**Comment by Code4SocialGood** [comment] 2017-07-07 23:53
@bshores This issue is resolved in PT #703. Please retest.

**Comment by Code4SocialGood** [comment] 2017-07-16 02:54
Issue is resolved in PR #703.

**Closed by Code4SocialGood** 2017-07-16 02:54 UTC
Labels: Test
