### ISSUE TITLE
Email Template Change

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1545] opened 2017-11-08 17:49 UTC
For the following email template: 
- Add a line to show user's profile: **Applicant Link:** 

- For **Applicant Slack**: Don't display the value of `"https://code4socialgood.slack.com/messages/@"` if there is no user's slack username append to it. See screen shot of how it looks like currently, We want to show blank is user has no slack username
![image](https://user-images.githubusercontent.com/24813620/32564746-cd5a4fa6-c47a-11e7-9048-c28c9fc9fcd0.png)

Code for Social Good: You received an application

![image](https://user-images.githubusercontent.com/24813620/32564477-fe3d9976-c479-11e7-8559-8d78d48564a9.png)

**Comment by professionalsql** [comment] 2017-11-15 03:59
The first line of this appears new, but the second bullet appears to be a duplicate of #1499. Should the the issues be merged?

**Comment by Code4SocialGood** [comment] 2017-11-15 19:52
**To Test from Frontend**
1. Login as nonprofit user:  testnonprofituser2@gmail.com / Opensource5social!
2. Create a project
3. Logout
4. Login as volunteer user:   testvolunteeruser2@gmail.com / Opensource5social! (you might need to open incognito window to login as another user)
5. Find the project that nonprofit user created, and apply
6. Login to the email address of nonprofit user: testnonprofituser2@gmail.com / Opensource5social!
7. Verify the email

**Comment by professionalsql** [comment] 2017-11-16 16:31
I notice that the other templates have a similar issue when the slack is for a specific user. For example, the accept/decline templates reference the orgUser.chatUsername, which has the same issue. Do we want to fix these also as part of this issue, backlog them separately, or just ignore that side of it?

**Comment by professionalsql** [comment] 2017-11-16 21:27
I made the assumption that we wanted to cover all 4 templates that follow this basic issue, and updated all 4. They will still include the "Applicant Slack:" or "Organization Contact Slack:" line, but it will be blank if the user doesn't have a chatName configured.. 
Changed 4 files in commit
Pull request issued
Will close on merge.

**Comment by professionalsql** [comment] 2017-11-17 16:33
Merge and closed 2017-11-16

**Closed by professionalsql** 2017-11-17 16:33 UTC
Labels: Backend, good first issue
