### ISSUE TITLE
Volunteer User - Opportunity description screen  Apply and Share button actions

### ISSUE THREAD

**Issue by sreelatha6** [Code4SocialGood/c4sg-web#334] opened 2017-05-21 02:36 UTC
Login as Volunteer User, URL - http://dev.code4socialgood.org/.
Click on Opportunities Menu
Click on one of the Opportunity header
Opportunities details screen displays
Click on  Apply button 
Expected ; Apply Action's corresponding screen should display
Actual - nothing happens after clicking on  "
<img width="897" alt="apply and share button click actions" src="https://cloud.githubusercontent.com/assets/28464814/26280697/d30fa6f8-3dac-11e7-9678-b960dd2ce753.PNG">
Apply"

**Comment by Code4SocialGood** [comment] 2017-05-24 15:53
- **Additional description on this issue**
This is what should happen when Apply button is clicked by volunteer user:
1. One row is inserted into user_project table
2. An email is sent to the nonprofit user who posted this project (logon to gmail with nonprofit user credential to check the email)
3. A toast is thrown: "You have applied for the project"

This issue is marked as full stack, we don't know whether the problem is on frontend or on backend.

@sreelatha6 Please create a document to maintain the messages:
- A list of error messages (such as: You must enter Project Name)
- A list of application messages (such as: Your project has been created)
The messages will be reviewed for consistency and for better wording.

**Comment by ameepandya** [comment] 2017-05-26 19:15
I see apply button is working. It gives notification that "Project is already applied for" or "Applied for project. The work needs to be done is just to make apply/bookmark button disable once it is already applied for that project.

**Comment by Code4SocialGood** [comment] 2017-06-01 05:31
Please make apply/bookmark button disabled once it is already applied/bookmarked for that project.

**Closed** 2017-06-19 03:23 UTC
