### ISSUE TITLE
"File in owners trash" error  in setup information guide

### ISSUE THREAD

**Issue by anajauregui** [Code4SocialGood/c4sg-web#1389] opened 2017-10-16 19:57 UTC
<img width="806" alt="screenshot 2017-10-16 13 53 34" src="https://user-images.githubusercontent.com/20731901/31632346-d11e1cf2-b279-11e7-8c2b-dec2445a4cd7.png">

Ran into this error upon trying to follow set up docs.

**Comment by Code4SocialGood** [comment] 2017-10-16 21:19
@anajauregui Thank you for creating this issue. We tested the link to the setup document, and couldn't reproduce the issue you experienced. However, as a best practice, we backed up the document in case we lose access to it later. 

Please let us know if you have issue accessing or opening this setup document.

![image](https://user-images.githubusercontent.com/24813620/31635729-78f2ae80-b28d-11e7-8485-d845431c128f.png)

**Comment by Code4SocialGood** [comment] 2017-10-18 18:34
Close this issue. Setup document is moved within github for easy management and change tracking.. See issue #1413 .

**Closed by Code4SocialGood** 2017-10-18 18:34 UTC
